### ISSUE TITLE
About OpenImagesV7

### ISSUE THREAD

**Issue by YongLD** [AnjieCheng/SpatialRGPT#11]
I discovered that the entire dataset contains 9 million images, but I saw that the code specifies 900K. Could you please clarify which subset of the data is being used? Downloading all 9 million images is too large to handle.
```python
        depth_path="/PATH/relative_depth/raw",
        description="900K SFT data by SpatialRGPT (submission) w/ depth (template+LLaMa rephrased).",
```

**Comment by AnjieCheng** [comment]
We are using a subset of OpenImages that contains 1.9 million images, so you only need to download that amount.
[https://storage.googleapis.com/openimages/web/download_v7.html#dense-labels-subset](https://storage.googleapis.com/openimages/web/download_v7.html#dense-labels-subset)
