### ISSUE TITLE
Regarding stage 2 training

### ISSUE THREAD

**Issue by wufeim** [AnjieCheng/SpatialRGPT#4]
Dear SpatialRGPT authors,

Thanks for sharing the codebase for SpatialRGPT. This is the description of the training in the paper:

> During the first stage, CC3M image- caption pairs are used to pretrain the RGB connector as [29, 51, 52]. In the second stage, the visual language corpus from MMC4 [53] and COYO [54] is used to pretrain the LLM and the RGB connector. The RGB connector and LLM parameters are then frozen, with only the depth connector trainable and pre-trained on our OSD dataset. Finally, at stage three, we fine-tune the pre-trained model on visual language instruction-following datasets, using a combination of the instruction tuning dataset from [29], region-level instruction tuning data [19], and our OSD dataset.

In second stage there seems to be two sub-stages, first tuning LLM and RGB connector and then tuning the depth connector. However, I don't see relevant code regarding the two sub-stages, i.e., freezing connector and LLM and tune depth connector only. Is this design adopted in this codebase or am I missing the code somewhere?

Thanks very much.

**Comment by AnjieCheng** [comment]
Hi, the current training script in the codebase is indeed as intended, condensing the training process into three stages and now supporting VILA-1.5. The released model also follows this simpler three-stage process, so the second stage is no longer split into separate parts. This makes the training process easier while keeping the same performance.

**Comment by wufeim** [comment]
Thanks for the clarification!
