### ISSUE TITLE
Some tips for setting up (needs fixing?)

### ISSUE THREAD

**Issue by kyuewang17** [AnjieCheng/SpatialRGPT#6]
1. Anaconda environment is not activated after running "environment_setup.sh" bash script.
  - Need to manually activate the conda env

2. Installing & building detectron2
  - after activating "srgpt-demo" env, CUDA=12.4 is set for the conda env (==> check "nvcc -V")
  - After activation, installing and building detectron2 via "pip install -U ~~~" fails.
  - I manually set CUDA version to 12.1 as in [here](https://github.com/facebookresearch/detectron2/issues/4992#issuecomment-1816949807)
  `export CUDA_HOME=/usr/local/cuda-12.1`
  `export PATH="${CUDA_HOME}/bin:$PATH"`
  `export LD_LIBRARY_PATH="${CUDA_HOME}/lib64:$LD_LIBRARY_PATH"`
  - Check CUDA version with "nvcc -V" again. (Changed to 12.1)
  - Now detectron2 part does not fail.

**Comment by AnjieCheng** [comment]
Hi, thank you for catching this! I've updated the instructions accordingly.
